### ISSUE TITLE
Download Mixed Content Error

### ISSUE THREAD

**Issue by ksherwoo** [AdobeDocs/experience-manager-document-security.en#2]
Hello,

It is not possible to download the Document Extensions here, either the EXE or MSI, without accessing the Developer Tools Console. If you check the Console messages, you will see that there is a Mixed Content error that prevents the user from just clicking on the file in the browser to download it. You have to access the link to the file which is embedded in the Mixed Content error and then the file will download as expected.

This should either be fixed or documented in the Release Notes.

Thanks,

Kate Sherwood | Senior Technical Support Specialist | 4Point | kate.sherwood@4point.com

![Download Mixed Content Error](https://user-images.githubusercontent.com/71287870/174899179-f15cfa87-459f-4bf5-822e-cfaa036d49ac.png)
e

**Comment by aheim0** [comment]
Thanks for raising this - we will review.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
Closing as this seems to be fixed.
